# tools/new_release.sh bobcat automaton bugfix
# tools/new_release.sh bobcat castellan bugfix
# tools/new_release.sh bobcat oslo.cache bugfix
# tools/new_release.sh bobcat oslo.concurrency bugfix
# tools/new_release.sh bobcat oslo.config bugfix
# tools/new_release.sh bobcat oslo.context bugfix
# tools/new_release.sh bobcat oslo.db bugfix
# tools/new_release.sh bobcat oslo.i18n bugfix
# tools/new_release.sh bobcat oslo.limit bugfix
# tools/new_release.sh bobcat oslo.log bugfix
# tools/new_release.sh bobcat oslo.messaging bugfix
# tools/new_release.sh bobcat oslo.metrics bugfix
# tools/new_release.sh bobcat oslo.middleware bugfix
# tools/new_release.sh bobcat oslo.policy bugfix
# tools/new_release.sh bobcat oslo.privsep bugfix
# tools/new_release.sh bobcat oslo.reports bugfix
# tools/new_release.sh bobcat oslo.rootwrap bugfix
# tools/new_release.sh bobcat oslo.serialization bugfix
# tools/new_release.sh bobcat oslo.service bugfix
# tools/new_release.sh bobcat oslo.upgradecheck bugfix
# tools/new_release.sh bobcat oslo.utils bugfix
# tools/new_release.sh bobcat oslo.versionedobjects bugfix
# tools/new_release.sh bobcat oslo.vmware bugfix
# tools/new_release.sh bobcat stevedore bugfix
# tools/new_release.sh bobcat taskflow bugfix
