# tools/new_release.sh independent renderspec bugfix
# tools/new_release.sh independent futurist bugfix
# tools/new_release.sh independent microversion-parse bugfix
# tools/new_release.sh independent openstack-doc-tools bugfix
# tools/new_release.sh independent openstackdocstheme bugfix
# tools/new_release.sh independent os-api-ref bugfix
# tools/new_release.sh independent oslo.concurrency bugfix
# tools/new_release.sh independent oslo.i18n bugfix
# tools/new_release.sh independent oslo.log bugfix
# tools/new_release.sh independent oslo.reports bugfix
# tools/new_release.sh independent oslo.rootwrap bugfix
# tools/new_release.sh independent oslotest bugfix
# tools/new_release.sh independent pbr bugfix
# tools/new_release.sh independent pylockfile bugfix
# tools/new_release.sh independent sphinx-feature-classification bugfix
# tools/new_release.sh independent taskflow bugfix
