# tools/new_release.sh wallaby automaton bugfix
# tools/new_release.sh wallaby castellan bugfix
# tools/new_release.sh wallaby oslo.cache bugfix
# tools/new_release.sh wallaby oslo.config bugfix
# tools/new_release.sh wallaby oslo.context bugfix
# tools/new_release.sh wallaby oslo.db bugfix
# tools/new_release.sh wallaby oslo.limit bugfix
# tools/new_release.sh wallaby oslo.messaging bugfix
# tools/new_release.sh wallaby oslo.metrics bugfix
# tools/new_release.sh wallaby oslo.middleware bugfix
# tools/new_release.sh wallaby oslo.policy bugfix
# tools/new_release.sh wallaby oslo.privsep bugfix
# tools/new_release.sh wallaby oslo.serialization bugfix
# tools/new_release.sh wallaby oslo.service bugfix
# tools/new_release.sh wallaby oslo.upgradecheck bugfix
# tools/new_release.sh wallaby oslo.utils bugfix
# tools/new_release.sh wallaby oslo.versionedobjects bugfix
# tools/new_release.sh wallaby oslo.vmware bugfix
# tools/new_release.sh wallaby stevedore bugfix
# tools/new_release.sh wallaby tooz bugfix
