# tools/new_release.sh victoria automaton bugfix
# tools/new_release.sh victoria castellan bugfix
# tools/new_release.sh victoria debtcollector bugfix
# tools/new_release.sh victoria devstack-plugin-amqp1 bugfix
# tools/new_release.sh victoria devstack-plugin-kafka bugfix
# tools/new_release.sh victoria futurist bugfix
# tools/new_release.sh victoria oslo.cache bugfix
# tools/new_release.sh victoria oslo.concurrency bugfix
# tools/new_release.sh victoria oslo.config bugfix
# tools/new_release.sh victoria oslo.context bugfix
# tools/new_release.sh victoria oslo.db bugfix
# tools/new_release.sh victoria oslo.i18n bugfix
# tools/new_release.sh victoria oslo.limit bugfix
# tools/new_release.sh victoria oslo.log bugfix
# tools/new_release.sh victoria oslo.messaging bugfix
# tools/new_release.sh victoria oslo.middleware bugfix
# tools/new_release.sh victoria oslo.policy bugfix
# tools/new_release.sh victoria oslo.privsep bugfix
# tools/new_release.sh victoria oslo.reports bugfix
# tools/new_release.sh victoria oslo.rootwrap bugfix
# tools/new_release.sh victoria oslo.serialization bugfix
# tools/new_release.sh victoria oslo.service bugfix
# tools/new_release.sh victoria oslo.upgradecheck bugfix
# tools/new_release.sh victoria oslo.utils bugfix
# tools/new_release.sh victoria oslo.versionedobjects bugfix
# tools/new_release.sh victoria oslo.vmware bugfix
# tools/new_release.sh victoria oslotest bugfix
# tools/new_release.sh victoria osprofiler bugfix
# tools/new_release.sh victoria stevedore bugfix
# tools/new_release.sh victoria taskflow bugfix
# tools/new_release.sh victoria tooz bugfix
