# tools/new_release.sh xena automaton bugfix
# tools/new_release.sh xena castellan bugfix
# tools/new_release.sh xena oslo.cache bugfix
# tools/new_release.sh xena oslo.config bugfix
# tools/new_release.sh xena oslo.context bugfix
# tools/new_release.sh xena oslo.db bugfix
# tools/new_release.sh xena oslo.limit bugfix
# tools/new_release.sh xena oslo.messaging bugfix
# tools/new_release.sh xena oslo.metrics bugfix
# tools/new_release.sh xena oslo.middleware bugfix
# tools/new_release.sh xena oslo.policy bugfix
# tools/new_release.sh xena oslo.privsep bugfix
# tools/new_release.sh xena oslo.serialization bugfix
# tools/new_release.sh xena oslo.service bugfix
# tools/new_release.sh xena oslo.upgradecheck bugfix
# tools/new_release.sh xena oslo.utils bugfix
# tools/new_release.sh xena oslo.versionedobjects bugfix
# tools/new_release.sh xena oslo.vmware bugfix
# tools/new_release.sh xena stevedore bugfix
