# tools/new_release.sh yoga automaton bugfix
# tools/new_release.sh yoga castellan bugfix
# tools/new_release.sh yoga oslo.cache bugfix
# tools/new_release.sh yoga oslo.config bugfix
# tools/new_release.sh yoga oslo.context bugfix
# tools/new_release.sh yoga oslo.db bugfix
# tools/new_release.sh yoga oslo.limit bugfix
# tools/new_release.sh yoga oslo.messaging bugfix
# tools/new_release.sh yoga oslo.metrics bugfix
# tools/new_release.sh yoga oslo.middleware bugfix
# tools/new_release.sh yoga oslo.policy bugfix
# tools/new_release.sh yoga oslo.privsep bugfix
# tools/new_release.sh yoga oslo.serialization bugfix
# tools/new_release.sh yoga oslo.service bugfix
# tools/new_release.sh yoga oslo.upgradecheck bugfix
# tools/new_release.sh yoga oslo.utils bugfix
# tools/new_release.sh yoga oslo.versionedobjects bugfix
# tools/new_release.sh yoga oslo.vmware bugfix
# tools/new_release.sh yoga stevedore bugfix
