# tools/new_release.sh ussuri automaton bugfix
# tools/new_release.sh ussuri castellan bugfix
# tools/new_release.sh ussuri debtcollector bugfix
# tools/new_release.sh ussuri devstack-plugin-amqp1 bugfix
# tools/new_release.sh ussuri devstack-plugin-kafka bugfix
# tools/new_release.sh ussuri futurist bugfix
# tools/new_release.sh ussuri mox3 bugfix
# tools/new_release.sh ussuri oslo.cache bugfix
# tools/new_release.sh ussuri oslo.concurrency bugfix
# tools/new_release.sh ussuri oslo.config bugfix
# tools/new_release.sh ussuri oslo.context bugfix
# tools/new_release.sh ussuri oslo.db bugfix
# tools/new_release.sh ussuri oslo.i18n bugfix
# tools/new_release.sh ussuri oslo.limit bugfix
# tools/new_release.sh ussuri oslo.log bugfix
# tools/new_release.sh ussuri oslo.messaging bugfix
# tools/new_release.sh ussuri oslo.middleware bugfix
# tools/new_release.sh ussuri oslo.policy bugfix
# tools/new_release.sh ussuri oslo.privsep bugfix
# tools/new_release.sh ussuri oslo.reports bugfix
# tools/new_release.sh ussuri oslo.rootwrap bugfix
# tools/new_release.sh ussuri oslo.serialization bugfix
# tools/new_release.sh ussuri oslo.service bugfix
# tools/new_release.sh ussuri oslo.upgradecheck bugfix
# tools/new_release.sh ussuri oslo.utils bugfix
# tools/new_release.sh ussuri oslo.versionedobjects bugfix
# tools/new_release.sh ussuri oslo.vmware bugfix
# tools/new_release.sh ussuri oslotest bugfix
# tools/new_release.sh ussuri osprofiler bugfix
# tools/new_release.sh ussuri stevedore bugfix
# tools/new_release.sh ussuri taskflow bugfix
# tools/new_release.sh ussuri tooz bugfix
