# tools/new_release.sh train automaton bugfix
# tools/new_release.sh train castellan bugfix
# tools/new_release.sh train debtcollector bugfix
# tools/new_release.sh train devstack-plugin-amqp1 bugfix
# tools/new_release.sh train devstack-plugin-kafka bugfix
# tools/new_release.sh train futurist bugfix
# tools/new_release.sh train mox3 bugfix
# tools/new_release.sh train oslo.cache bugfix
# tools/new_release.sh train oslo.concurrency bugfix
# tools/new_release.sh train oslo.config bugfix
# tools/new_release.sh train oslo.context bugfix
# tools/new_release.sh train oslo.db bugfix
# tools/new_release.sh train oslo.i18n bugfix
# tools/new_release.sh train oslo.limit bugfix
# tools/new_release.sh train oslo.log bugfix
# tools/new_release.sh train oslo.messaging bugfix
# tools/new_release.sh train oslo.middleware bugfix
# tools/new_release.sh train oslo.policy bugfix
# tools/new_release.sh train oslo.privsep bugfix
# tools/new_release.sh train oslo.reports bugfix
# tools/new_release.sh train oslo.rootwrap bugfix
# tools/new_release.sh train oslo.serialization bugfix
# tools/new_release.sh train oslo.service bugfix
# tools/new_release.sh train oslo.upgradecheck bugfix
# tools/new_release.sh train oslo.utils bugfix
# tools/new_release.sh train oslo.versionedobjects bugfix
# tools/new_release.sh train oslo.vmware bugfix
# tools/new_release.sh train oslotest bugfix
# tools/new_release.sh train osprofiler bugfix
# tools/new_release.sh train stevedore bugfix
# tools/new_release.sh train taskflow bugfix
# tools/new_release.sh train tooz bugfix
