# tools/new_release.sh antelope automaton bugfix
# tools/new_release.sh antelope castellan bugfix
# tools/new_release.sh antelope oslo.cache bugfix
# tools/new_release.sh antelope oslo.concurrency bugfix
# tools/new_release.sh antelope oslo.config bugfix
# tools/new_release.sh antelope oslo.context bugfix
# tools/new_release.sh antelope oslo.db bugfix
# tools/new_release.sh antelope oslo.i18n bugfix
# tools/new_release.sh antelope oslo.limit bugfix
# tools/new_release.sh antelope oslo.log bugfix
# tools/new_release.sh antelope oslo.messaging bugfix
# tools/new_release.sh antelope oslo.metrics bugfix
# tools/new_release.sh antelope oslo.middleware bugfix
# tools/new_release.sh antelope oslo.policy bugfix
# tools/new_release.sh antelope oslo.privsep bugfix
# tools/new_release.sh antelope oslo.reports bugfix
# tools/new_release.sh antelope oslo.rootwrap bugfix
# tools/new_release.sh antelope oslo.serialization bugfix
# tools/new_release.sh antelope oslo.service bugfix
# tools/new_release.sh antelope oslo.upgradecheck bugfix
# tools/new_release.sh antelope oslo.utils bugfix
# tools/new_release.sh antelope oslo.versionedobjects bugfix
# tools/new_release.sh antelope oslo.vmware bugfix
# tools/new_release.sh antelope stevedore bugfix
# tools/new_release.sh antelope taskflow bugfix
